/**
 * Lightweight client-side i18n. The brand display language is chosen by the
 * visitor (persisted to cookie + localStorage). Falls back to English for any
 * missing key. Translations are stored per-key (all locales together) for
 * maintainability.
 */

import { CATALOG } from "@/lib/catalog-i18n";

export type Locale = "en" | "zh" | "es" | "pt" | "ru" | "fil";

export interface LocaleMeta {
  code: Locale;
  label: string;
  english: string;
}

export const LOCALES: LocaleMeta[] = [
  { code: "en", label: "English (Global)", english: "English" },
  { code: "zh", label: "简体中文", english: "Chinese (Simplified)" },
  { code: "es", label: "Español", english: "Spanish" },
  { code: "pt", label: "Português", english: "Portuguese" },
  { code: "ru", label: "Русский", english: "Russian" },
  { code: "fil", label: "Filipino", english: "Filipino" },
];

export const LOCALE_CODES: Locale[] = LOCALES.map((l) => l.code);

export function isLocale(v: unknown): v is Locale {
  return typeof v === "string" && (LOCALE_CODES as string[]).includes(v);
}

type Entry = Record<Locale, string>;

/** key → translations. English is the source of truth + fallback. */
const T: Record<string, Entry> = {
  // ── Navigation ──────────────────────────────────────────────
  "nav.services": { en: "Services", zh: "服务", es: "Servicios", pt: "Serviços", ru: "Услуги", fil: "Mga Serbisyo" },
  "nav.pricing": { en: "Pricing", zh: "价格", es: "Precios", pt: "Preços", ru: "Цены", fil: "Presyo" },
  "nav.track": { en: "Track Order", zh: "订单追踪", es: "Seguir pedido", pt: "Rastrear pedido", ru: "Отследить заказ", fil: "Subaybayan ang Order" },
  "nav.signin": { en: "Sign in", zh: "登录", es: "Iniciar sesión", pt: "Entrar", ru: "Войти", fil: "Mag-sign in" },
  "nav.getStarted": { en: "Get Started", zh: "立即开始", es: "Comenzar", pt: "Começar", ru: "Начать", fil: "Magsimula" },
  "nav.dashboard": { en: "Dashboard", zh: "控制台", es: "Panel", pt: "Painel", ru: "Кабинет", fil: "Dashboard" },

  // ── Common ──────────────────────────────────────────────────
  "common.cancel": { en: "Cancel", zh: "取消", es: "Cancelar", pt: "Cancelar", ru: "Отмена", fil: "Kanselahin" },
  "common.save": { en: "Save changes", zh: "保存更改", es: "Guardar cambios", pt: "Salvar alterações", ru: "Сохранить", fil: "I-save ang mga pagbabago" },
  "common.viewDetails": { en: "View details", zh: "查看详情", es: "Ver detalles", pt: "Ver detalhes", ru: "Подробнее", fil: "Tingnan ang detalye" },
  "common.startingFrom": { en: "Starting from", zh: "起价", es: "Desde", pt: "A partir de", ru: "От", fil: "Mula sa" },

  // ── Region modal ────────────────────────────────────────────
  "region.title": { en: "Language & Region", zh: "语言与地区", es: "Idioma y región", pt: "Idioma e região", ru: "Язык и регион", fil: "Wika at Rehiyon" },
  "region.subtitle": { en: "Choose your currency and preferred regional storefront.", zh: "选择您的货币和首选的地区商店。", es: "Elige tu moneda y tu tienda regional preferida.", pt: "Escolha sua moeda e a loja regional preferida.", ru: "Выберите валюту и предпочитаемый региональный магазин.", fil: "Piliin ang iyong currency at gustong rehiyonal na storefront." },
  "region.language": { en: "Language", zh: "语言", es: "Idioma", pt: "Idioma", ru: "Язык", fil: "Wika" },
  "region.currency": { en: "Currency", zh: "货币", es: "Moneda", pt: "Moeda", ru: "Валюта", fil: "Currency" },
  "region.estimate": { en: "Prices in other currencies are estimates. All orders are charged in ₱ PHP.", zh: "其他货币价格为估算值。所有订单均以 ₱ 菲律宾比索结算。", es: "Los precios en otras monedas son estimaciones. Todos los pedidos se cobran en ₱ PHP.", pt: "Preços em outras moedas são estimativas. Todos os pedidos são cobrados em ₱ PHP.", ru: "Цены в других валютах являются ориентировочными. Все заказы оплачиваются в ₱ PHP.", fil: "Ang presyo sa ibang currency ay tantya lang. Lahat ng order ay sinisingil sa ₱ PHP." },

  // ── Hero ────────────────────────────────────────────────────
  "hero.subtitle": { en: "Premium Dota 2 Services Worldwide", zh: "全球高端 Dota 2 代练服务", es: "Servicios premium de Dota 2 en todo el mundo", pt: "Serviços premium de Dota 2 em todo o mundo", ru: "Премиальные услуги Dota 2 по всему миру", fil: "Premium na Dota 2 Services sa Buong Mundo" },
  "hero.trusted": { en: "Trusted by Dota 2 Players Worldwide", zh: "深受全球 Dota 2 玩家信赖", es: "La confianza de jugadores de Dota 2 en todo el mundo", pt: "A confiança de jogadores de Dota 2 no mundo todo", ru: "Нам доверяют игроки Dota 2 по всему миру", fil: "Pinagkakatiwalaan ng mga Dota 2 Player sa buong mundo" },
  "cta.calculate": { en: "Calculate Your Boost", zh: "计算代练价格", es: "Calcula tu boost", pt: "Calcule seu boost", ru: "Рассчитать буст", fil: "Kalkulahin ang Boost" },
  "cta.explore": { en: "Explore Services", zh: "浏览服务", es: "Explorar servicios", pt: "Explorar serviços", ru: "Смотреть услуги", fil: "Tuklasin ang mga Serbisyo" },
  "hero.titleMain": { en: "Reach Your Desired Rank", zh: "更快到达你的", es: "Alcanza tu rango deseado", pt: "Alcance o rank que você quer", ru: "Достигайте желаемого ранга", fil: "Abutin ang gusto mong rank nang" },
  "hero.titleAccent": { en: "Faster.", zh: "理想段位。", es: "más rápido.", pt: "mais rápido.", ru: "быстрее.", fil: "mas mabilis." },
  "hero.badgeFull": { en: "Premium Dota 2 boosting — now serving players worldwide", zh: "高端 Dota 2 代练 —— 现已服务全球玩家", es: "Boost premium de Dota 2: ahora para jugadores de todo el mundo", pt: "Boost premium de Dota 2 — agora para jogadores do mundo todo", ru: "Премиум-буст Dota 2 — теперь для игроков по всему миру", fil: "Premium na Dota 2 boosting — para na sa mga player sa buong mundo" },
  "hero.badgeShort": { en: "Premium Dota 2 boosting · worldwide", zh: "高端 Dota 2 代练 · 全球", es: "Boost premium de Dota 2 · mundial", pt: "Boost premium de Dota 2 · mundial", ru: "Премиум-буст Dota 2 · по миру", fil: "Premium na Dota 2 boosting · worldwide" },
  "hero.tagline": { en: "Trusted by Dota 2 Players Worldwide — professional boosting available globally.", zh: "深受全球 Dota 2 玩家信赖 —— 专业代练服务覆盖全球。", es: "La confianza de jugadores de Dota 2 en todo el mundo — boost profesional disponible globalmente.", pt: "A confiança de jogadores de Dota 2 no mundo todo — boost profissional disponível globalmente.", ru: "Нам доверяют игроки Dota 2 по всему миру — профессиональный буст доступен глобально.", fil: "Pinagkakatiwalaan ng mga Dota 2 Player sa buong mundo — propesyonal na boosting na available globally." },
  "hero.offerPre": { en: "First order: save", zh: "首单立减", es: "Primer pedido: ahorra", pt: "Primeiro pedido: economize", ru: "Первый заказ: скидка", fil: "Unang order: tipid ng" },
  "hero.offerSuf": { en: "— applied automatically at checkout", zh: "—— 结账时自动应用", es: "— se aplica automáticamente al pagar", pt: "— aplicado automaticamente no checkout", ru: "— применяется автоматически при оплате", fil: "— awtomatikong ma-a-apply sa checkout" },
  "live.m1": { en: "12 players online now", zh: "12 位玩家在线", es: "12 jugadores en línea ahora", pt: "12 jogadores online agora", ru: "12 игроков онлайн", fil: "12 players online ngayon" },
  "live.m2": { en: "5 orders completed today", zh: "今日已完成 5 笔订单", es: "5 pedidos completados hoy", pt: "5 pedidos concluídos hoje", ru: "5 заказов выполнено сегодня", fil: "5 order na natapos ngayong araw" },
  "live.m3": { en: "24 verified boosters available", zh: "24 名认证代练可用", es: "24 boosters verificados disponibles", pt: "24 boosters verificados disponíveis", ru: "24 проверенных бустера доступно", fil: "24 verified booster ang available" },
  "live.m4": { en: "3 boosts started in the last hour", zh: "过去一小时内开始了 3 单代练", es: "3 boosts iniciados en la última hora", pt: "3 boosts iniciados na última hora", ru: "3 буста начато за последний час", fil: "3 boost na nagsimula sa nakaraang oras" },
  "calc.extraOptions": { en: "Extra Options", zh: "附加选项", es: "Opciones extra", pt: "Opções extras", ru: "Доп. опции", fil: "Karagdagang Opsyon" },
  "calc.quantity": { en: "Quantity", zh: "数量", es: "Cantidad", pt: "Quantidade", ru: "Количество", fil: "Dami" },

  // ── Purchase protection (RankUpPH Shield) ───────────────────
  "pp.title": { en: "How we protect your purchase", zh: "我们如何保护您的购买", es: "Cómo protegemos tu compra", pt: "Como protegemos sua compra", ru: "Как мы защищаем вашу покупку", fil: "Paano namin pinoprotektahan ang binili mo" },
  "pp.i1.t": { en: "Your account stays private", zh: "您的账号保持私密", es: "Tu cuenta se mantiene privada", pt: "Sua conta permanece privada", ru: "Ваш аккаунт остаётся приватным", fil: "Private ang account mo" },
  "pp.i1.d": { en: "Boosters play through a region-matched VPN in offline mode — invisible to your friends, clubs, and recent teammates.", zh: "代练通过与地区匹配的 VPN 以离线模式游戏——对您的好友、战队和近期队友隐身。", es: "Los boosters juegan con una VPN de tu región en modo offline, invisibles para amigos, clubes y compañeros recientes.", pt: "Os boosters jogam com uma VPN da sua região em modo offline — invisíveis para amigos, clubes e colegas recentes.", ru: "Бустеры играют через VPN вашего региона в офлайн-режиме — невидимы для друзей, клубов и недавних тиммейтов.", fil: "Naglalaro ang boosters sa region-matched VPN sa offline mode — hindi nakikita ng mga kaibigan, club, at kakalaro." },
  "pp.i2.t": { en: "Money-back guarantee", zh: "退款保证", es: "Garantía de devolución", pt: "Garantia de reembolso", ru: "Гарантия возврата денег", fil: "Money-back guarantee" },
  "pp.i2.d": { en: "Every order is backed by our refund promise. If something doesn't go to plan, we make it right — no runaround.", zh: "每笔订单都有我们的退款承诺。如果出现问题，我们会妥善解决——绝不推诿。", es: "Cada pedido cuenta con nuestra promesa de reembolso. Si algo no sale según lo previsto, lo arreglamos — sin vueltas.", pt: "Cada pedido tem nossa promessa de reembolso. Se algo não sair como planejado, resolvemos — sem enrolação.", ru: "Каждый заказ обеспечен нашей гарантией возврата. Если что-то пойдёт не так, мы всё исправим — без отговорок.", fil: "Bawat order ay may refund promise namin. Kung may mali, aayusin namin — walang paikot-ikot." },
  "pp.i3.t": { en: "24/7 live support", zh: "全天候在线支持", es: "Soporte en vivo 24/7", pt: "Suporte ao vivo 24/7", ru: "Поддержка 24/7", fil: "24/7 live support" },
  "pp.i3.d": { en: "Chat directly with your booster and reach a real person any hour. You're updated at every step, never left guessing.", zh: "随时直接与您的代练沟通，联系真人客服。每一步都有更新，绝不让您猜测。", es: "Chatea con tu booster y contacta a una persona real a cualquier hora. Te actualizamos en cada paso, sin dejarte con dudas.", pt: "Converse com seu booster e fale com uma pessoa real a qualquer hora. Você é atualizado a cada passo, sem dúvidas.", ru: "Общайтесь с бустером и связывайтесь с живым человеком в любое время. Вас держат в курсе на каждом шаге.", fil: "Makipag-chat sa booster mo at sa tunay na tao anumang oras. May update ka sa bawat hakbang, walang hula-hula." },
  "pp.i4.t": { en: "Bank-grade encryption", zh: "银行级加密", es: "Cifrado de nivel bancario", pt: "Criptografia de nível bancário", ru: "Банковское шифрование", fil: "Bank-grade na encryption" },
  "pp.i4.d": { en: "Payments run through Stripe (PCI-DSS), and your Steam credentials are encrypted at rest with AES-256 — only your booster can see them.", zh: "支付通过 Stripe（PCI-DSS）处理，您的 Steam 凭证以 AES-256 静态加密——只有您的代练可以看到。", es: "Los pagos pasan por Stripe (PCI-DSS) y tus credenciales de Steam se cifran con AES-256 — solo tu booster las ve.", pt: "Os pagamentos passam pela Stripe (PCI-DSS) e suas credenciais da Steam são criptografadas com AES-256 — só seu booster as vê.", ru: "Платежи проходят через Stripe (PCI-DSS), а данные Steam шифруются AES-256 — их видит только ваш бустер.", fil: "Dumadaan ang bayad sa Stripe (PCI-DSS), at naka-encrypt ang Steam credentials mo gamit ang AES-256 — booster mo lang ang makakakita." },

  // ── Global trust strip ──────────────────────────────────────
  "trust.s1": { en: "Global Service Coverage", zh: "全球服务覆盖", es: "Cobertura global", pt: "Cobertura global", ru: "Глобальное покрытие", fil: "Global na Saklaw" },
  "trust.s2": { en: "Secure Stripe Payments", zh: "安全的 Stripe 支付", es: "Pagos seguros con Stripe", pt: "Pagamentos seguros via Stripe", ru: "Безопасные платежи Stripe", fil: "Secure na Stripe Payments" },
  "trust.s3": { en: "GCash Supported", zh: "支持 GCash", es: "Compatible con GCash", pt: "Suporte a GCash", ru: "Поддержка GCash", fil: "Suportado ang GCash" },
  "trust.s4": { en: "Verified High-Rank Boosters", zh: "经过认证的高分代练", es: "Boosters verificados de alto rango", pt: "Boosters verificados de alto rank", ru: "Проверенные высокоранговые бустеры", fil: "Verified na High-Rank Boosters" },
  "trust.s5": { en: "Real-Time Order Tracking", zh: "实时订单追踪", es: "Seguimiento de pedidos en tiempo real", pt: "Rastreamento de pedidos em tempo real", ru: "Отслеживание заказа в реальном времени", fil: "Real-Time na Pag-track ng Order" },
  "trust.s6": { en: "24/7 Customer Support", zh: "全天候客户支持", es: "Soporte 24/7", pt: "Suporte 24/7", ru: "Поддержка 24/7", fil: "24/7 na Suporta" },
  "trust.s7": { en: "Worldwide Availability", zh: "全球可用", es: "Disponibilidad mundial", pt: "Disponibilidade mundial", ru: "Доступно по всему миру", fil: "Available sa Buong Mundo" },
  "trust.stat1": { en: "MMR Boosted", zh: "已提升 MMR", es: "MMR aumentado", pt: "MMR aumentado", ru: "Поднято MMR", fil: "MMR na Na-boost" },
  "trust.stat2": { en: "Completed Orders", zh: "已完成订单", es: "Pedidos completados", pt: "Pedidos concluídos", ru: "Выполнено заказов", fil: "Natapos na Order" },
  "trust.stat3": { en: "Satisfaction Rate", zh: "满意度", es: "Índice de satisfacción", pt: "Índice de satisfação", ru: "Уровень удовлетворённости", fil: "Satisfaction Rate" },
  "trust.para": { en: "From SEA grinders to EU, NA, and beyond — RankUpPH helps players across all major Dota 2 regions reach their goals faster through professional boosting and calibration services. Competitive pricing. Global coverage.", zh: "从东南亚的玩家到欧洲、北美及更多地区——RankUpPH 通过专业的代练和定位服务，帮助所有主要 Dota 2 服务器的玩家更快地实现目标。价格实惠，全球覆盖。", es: "Desde los jugadores del Sudeste Asiático hasta Europa, Norteamérica y más allá: RankUpPH ayuda a jugadores de todas las grandes regiones de Dota 2 a alcanzar sus metas más rápido con servicios profesionales de boost y calibración. Precios competitivos. Cobertura global.", pt: "Dos jogadores do Sudeste Asiático à Europa, América do Norte e além — a RankUpPH ajuda jogadores de todas as grandes regiões de Dota 2 a alcançarem suas metas mais rápido com serviços profissionais de boost e calibração. Preços competitivos. Cobertura global.", ru: "От игроков Юго-Восточной Азии до Европы, Северной Америки и далее — RankUpPH помогает игрокам во всех основных регионах Dota 2 быстрее достигать целей с помощью профессионального буста и калибровки. Конкурентные цены. Глобальное покрытие.", fil: "Mula sa mga manlalaro ng SEA hanggang EU, NA, at higit pa — tinutulungan ng RankUpPH ang mga manlalaro sa lahat ng pangunahing rehiyon ng Dota 2 na maabot ang kanilang mga layunin nang mas mabilis sa pamamagitan ng propesyonal na boosting at calibration. Competitive na presyo. Global na saklaw." },

  // ── Section headings ────────────────────────────────────────
  "sec.services.eyebrow": { en: "Our Services", zh: "我们的服务", es: "Nuestros servicios", pt: "Nossos serviços", ru: "Наши услуги", fil: "Aming mga Serbisyo" },
  "sec.services.lead": { en: "Three ways to", zh: "三种上分方式", es: "Tres formas de", pt: "Três formas de", ru: "Три пути", fil: "Tatlong paraan para" },
  "sec.services.accent": { en: "climb.", zh: "—— 任你选。", es: "subir.", pt: "subir.", ru: "наверх.", fil: "umakyat." },
  "sec.services.desc": { en: "Whatever your goal — a higher medal, safer progress, or sharper skills — we have a premium service built for it.", zh: "无论您的目标是更高的段位、更安全的进度，还是更强的技术——我们都有为之打造的高端服务。", es: "Sea cual sea tu objetivo —una medalla más alta, un progreso más seguro o mejores habilidades— tenemos un servicio premium para ello.", pt: "Seja qual for seu objetivo — uma medalha mais alta, progresso mais seguro ou habilidades melhores — temos um serviço premium para isso.", ru: "Какой бы ни была ваша цель — более высокая медаль, безопасный прогресс или прокачка навыков — у нас есть премиум-услуга для этого.", fil: "Anuman ang iyong layunin — mas mataas na medalya, mas ligtas na progreso, o mas matalas na skill — may premium na serbisyo kami para diyan." },
  "sec.how.eyebrow": { en: "How It Works", zh: "运作方式", es: "Cómo funciona", pt: "Como funciona", ru: "Как это работает", fil: "Paano Ito Gumagana" },
  "sec.how.lead": { en: "From order to victory in", zh: "从下单到胜利，只需", es: "Del pedido a la victoria en", pt: "Do pedido à vitória em", ru: "От заказа до победы за", fil: "Mula order hanggang panalo sa" },
  "sec.how.accent": { en: "3 steps.", zh: "3 步。", es: "3 pasos.", pt: "3 passos.", ru: "3 шага.", fil: "3 hakbang." },
  "sec.how.desc": { en: "A frictionless, transparent process designed so you always know exactly what's happening with your climb.", zh: "流畅、透明的流程，让您始终清楚地了解上分进度。", es: "Un proceso fluido y transparente diseñado para que siempre sepas exactamente qué pasa con tu subida.", pt: "Um processo fluido e transparente para que você sempre saiba exatamente o que acontece com sua subida.", ru: "Простой и прозрачный процесс, чтобы вы всегда точно знали, что происходит с вашим прогрессом.", fil: "Maayos at transparent na proseso para palaging alam mo kung ano ang nangyayari sa iyong pag-akyat." },
  "sec.calc.eyebrow": { en: "Instant Pricing", zh: "即时报价", es: "Precio instantáneo", pt: "Preço instantâneo", ru: "Мгновенная цена", fil: "Agad na Presyo" },
  "sec.calc.lead": { en: "Know your price", zh: "在下单前", es: "Conoce tu precio", pt: "Saiba seu preço", ru: "Узнайте цену", fil: "Alamin ang presyo" },
  "sec.calc.accent": { en: "before you commit.", zh: "就知道价格。", es: "antes de decidir.", pt: "antes de decidir.", ru: "до оформления.", fil: "bago mag-commit." },
  "sec.calc.desc": { en: "No hidden fees, no surprises. Configure your order and watch the price update live — every value is rank- and option-based.", zh: "没有隐藏费用，没有意外。配置您的订单，实时查看价格更新——每一项都基于段位和选项计算。", es: "Sin tarifas ocultas ni sorpresas. Configura tu pedido y mira el precio en vivo — todo se basa en el rango y las opciones.", pt: "Sem taxas ocultas, sem surpresas. Configure seu pedido e veja o preço ao vivo — tudo é baseado em rank e opções.", ru: "Без скрытых комиссий и сюрпризов. Настройте заказ и смотрите цену вживую — всё зависит от ранга и опций.", fil: "Walang hidden fees, walang sorpresa. I-configure ang order at tingnan ang live na presyo — base lahat sa rank at opsyon." },
  "sec.reviews.eyebrow": { en: "Reviews", zh: "用户评价", es: "Reseñas", pt: "Avaliações", ru: "Отзывы", fil: "Mga Review" },
  "sec.reviews.lead": { en: "Loved by climbers", zh: "深受上分玩家", es: "Querido por quienes suben", pt: "Amado por quem sobe", ru: "Любят те, кто поднимается", fil: "Mahal ng mga umaakyat" },
  "sec.reviews.accent": { en: "across the ranks.", zh: "的喜爱。", es: "en todos los rangos.", pt: "em todos os ranks.", ru: "по всем рангам.", fil: "sa lahat ng rank." },
  "sec.reviews.desc": { en: "Real results from real players. Every review comes from a completed, verified order.", zh: "来自真实玩家的真实成果。每条评价都来自已完成且经过验证的订单。", es: "Resultados reales de jugadores reales. Cada reseña proviene de un pedido completado y verificado.", pt: "Resultados reais de jogadores reais. Cada avaliação vem de um pedido concluído e verificado.", ru: "Реальные результаты реальных игроков. Каждый отзыв — от завершённого, проверенного заказа.", fil: "Tunay na resulta mula sa tunay na manlalaro. Bawat review ay galing sa natapos at verified na order." },
  "sec.reviews.from": { en: "from verified orders", zh: "来自已验证订单", es: "de pedidos verificados", pt: "de pedidos verificados", ru: "от проверенных заказов", fil: "mula sa verified na order" },
  "sec.why.eyebrow": { en: "Why RankUpPH", zh: "为何选择 RankUpPH", es: "Por qué RankUpPH", pt: "Por que a RankUpPH", ru: "Почему RankUpPH", fil: "Bakit RankUpPH" },
  "sec.why.lead": { en: "Built on trust.", zh: "建立在信任之上。", es: "Hecho con confianza.", pt: "Construído na confiança.", ru: "Основано на доверии.", fil: "Itinayo sa tiwala." },
  "sec.why.accent": { en: "Engineered for results.", zh: "为成果而打造。", es: "Diseñado para resultados.", pt: "Projetado para resultados.", ru: "Создано для результата.", fil: "Ginawa para sa resulta." },
  "sec.why.desc": { en: "We treat your account and your money with the seriousness they deserve. This is a premium service — and it shows in every detail.", zh: "我们以应有的严谨态度对待您的账号和资金。这是高端服务——体现在每一个细节中。", es: "Tratamos tu cuenta y tu dinero con la seriedad que merecen. Es un servicio premium, y se nota en cada detalle.", pt: "Tratamos sua conta e seu dinheiro com a seriedade que merecem. É um serviço premium — e isso se vê em cada detalhe.", ru: "Мы относимся к вашему аккаунту и деньгам со всей серьёзностью. Это премиум-сервис — и это видно в каждой детали.", fil: "Sineseryoso namin ang iyong account at pera. Premium na serbisyo ito — at kita iyon sa bawat detalye." },
  "sec.guarantees.eyebrow": { en: "Our Promise", zh: "我们的承诺", es: "Nuestra promesa", pt: "Nossa promessa", ru: "Наше обещание", fil: "Aming Pangako" },
  "sec.guarantees.lead": { en: "Built to be", zh: "值得", es: "Hecho para ser", pt: "Feito para ser", ru: "Создано, чтобы", fil: "Ginawa para" },
  "sec.guarantees.accent": { en: "trusted.", zh: "信赖。", es: "de confianza.", pt: "confiável.", ru: "доверять.", fil: "pagkatiwalaan." },
  "sec.guarantees.desc": { en: "Premium service means premium protection. Here's what every order comes with — guaranteed.", zh: "高端服务意味着高端保障。以下是每笔订单都包含的内容——有保证。", es: "Servicio premium significa protección premium. Esto incluye cada pedido, garantizado.", pt: "Serviço premium significa proteção premium. Veja o que cada pedido inclui — garantido.", ru: "Премиум-сервис — это премиум-защита. Вот что входит в каждый заказ — гарантированно.", fil: "Premium na serbisyo, premium na proteksyon. Ito ang kasama sa bawat order — garantisado." },
  "sec.faq.eyebrow": { en: "FAQ", zh: "常见问题", es: "Preguntas frecuentes", pt: "Perguntas frequentes", ru: "Частые вопросы", fil: "FAQ" },
  "sec.faq.lead": { en: "Questions,", zh: "你的疑问，", es: "Preguntas,", pt: "Perguntas,", ru: "Вопросы,", fil: "Mga tanong," },
  "sec.faq.accent": { en: "answered.", zh: "我们来解答。", es: "respondidas.", pt: "respondidas.", ru: "ответы.", fil: "may sagot." },
  "sec.faq.desc": { en: "Everything you need to know before you climb. Still curious? Our support team is one message away.", zh: "上分前你需要知道的一切。还有疑问？我们的支持团队随时为您服务。", es: "Todo lo que necesitas saber antes de subir. ¿Aún tienes dudas? Nuestro equipo de soporte está a un mensaje.", pt: "Tudo o que você precisa saber antes de subir. Ainda com dúvidas? Nosso suporte está a uma mensagem de distância.", ru: "Всё, что нужно знать перед подъёмом. Остались вопросы? Поддержка на расстоянии одного сообщения.", fil: "Lahat ng kailangan mong malaman bago umakyat. May tanong pa? Isang mensahe lang ang aming support team." },

  // ── How It Works steps ──────────────────────────────────────
  "how.s1.title": { en: "Choose Your Service", zh: "选择服务", es: "Elige tu servicio", pt: "Escolha seu serviço", ru: "Выберите услугу", fil: "Piliin ang Serbisyo" },
  "how.s1.desc": { en: "Pick MMR boost, duo queue, or coaching. Set your current and target rank in seconds with our live calculator.", zh: "选择 MMR 代练、双排或教学。用我们的实时计算器在几秒内设置当前和目标段位。", es: "Elige boost de MMR, dúo o coaching. Fija tu rango actual y objetivo en segundos con nuestra calculadora.", pt: "Escolha boost de MMR, dupla ou coaching. Defina seu rank atual e alvo em segundos com nossa calculadora.", ru: "Выберите буст MMR, дуо или коучинг. Задайте текущий и целевой ранг за секунды с нашим калькулятором.", fil: "Pumili ng MMR boost, duo queue, o coaching. Itakda ang kasalukuyan at target na rank sa ilang segundo." },
  "how.s2.title": { en: "Complete Payment", zh: "完成付款", es: "Completa el pago", pt: "Conclua o pagamento", ru: "Оплатите", fil: "Kumpletuhin ang Bayad" },
  "how.s2.desc": { en: "Pay securely via Stripe or GCash. Your order is confirmed the moment payment clears — no risk, full transparency.", zh: "通过 Stripe 或 GCash 安全付款。付款到账即确认订单——无风险，完全透明。", es: "Paga de forma segura con Stripe o GCash. Tu pedido se confirma al recibirse el pago — sin riesgo, total transparencia.", pt: "Pague com segurança via Stripe ou GCash. Seu pedido é confirmado assim que o pagamento é compensado — sem risco, total transparência.", ru: "Оплатите безопасно через Stripe или GCash. Заказ подтверждается сразу после оплаты — без риска, полная прозрачность.", fil: "Magbayad nang ligtas via Stripe o GCash. Kumpirmado ang order pagdating ng bayad — walang risk, fully transparent." },
  "how.s3.title": { en: "Reach Your Goal", zh: "达成目标", es: "Alcanza tu meta", pt: "Alcance sua meta", ru: "Достигните цели", fil: "Abutin ang Layunin" },
  "how.s3.desc": { en: "A verified Immortal booster gets assigned. Track progress live, chat directly, and confirm when you hit your rank.", zh: "我们会分配一名经过认证的万古代练。实时跟踪进度、直接沟通，达到段位后确认即可。", es: "Se asigna un booster Inmortal verificado. Sigue el progreso en vivo, chatea y confirma al alcanzar tu rango.", pt: "Um booster Immortal verificado é designado. Acompanhe ao vivo, converse e confirme ao atingir seu rank.", ru: "Назначается проверенный бустер уровня Immortal. Следите за прогрессом, общайтесь и подтверждайте при достижении ранга.", fil: "May ita-assign na verified Immortal booster. I-track ang progreso, mag-chat, at i-confirm kapag naabot ang rank." },

  // ── Why reasons ─────────────────────────────────────────────
  "why.r1.title": { en: "Experienced Players", zh: "经验丰富的玩家", es: "Jugadores experimentados", pt: "Jogadores experientes", ru: "Опытные игроки", fil: "Eksperyensadong Player" },
  "why.r1.desc": { en: "Every booster is a verified Immortal with a proven track record. We vet skill, reliability, and discretion before anyone touches an account.", zh: "每位代练都是经过认证、战绩可查的万古玩家。我们在任何人接触账号前都会审核其技术、可靠性和保密性。", es: "Cada booster es un Inmortal verificado con historial comprobado. Evaluamos habilidad, fiabilidad y discreción antes de tocar una cuenta.", pt: "Cada booster é um Immortal verificado com histórico comprovado. Avaliamos habilidade, confiabilidade e discrição antes de tocar em uma conta.", ru: "Каждый бустер — проверенный Immortal с подтверждённой историей. Мы оцениваем навыки, надёжность и тактичность.", fil: "Bawat booster ay verified Immortal na may patunay na track record. Sinusuri namin ang skill, reliability, at discretion bago hawakan ang account." },
  "why.r2.title": { en: "Automated VPN Protection", zh: "自动 VPN 保护", es: "Protección VPN automática", pt: "Proteção VPN automática", ru: "Автоматическая VPN-защита", fil: "Automated VPN Protection" },
  "why.r2.desc": { en: "Every session runs through a region-matched VPN, keeping your login pattern clean and your account shielded the entire time.", zh: "每次代练都通过与您所在地区匹配的 VPN 进行，保持登录记录干净，全程保护您的账号。", es: "Cada sesión usa una VPN de tu región, manteniendo limpio tu patrón de inicio y tu cuenta protegida todo el tiempo.", pt: "Cada sessão usa uma VPN da sua região, mantendo seu padrão de login limpo e sua conta protegida o tempo todo.", ru: "Каждая сессия идёт через VPN вашего региона, сохраняя чистую историю входов и защищая аккаунт всё время.", fil: "Bawat session ay dumadaan sa region-matched VPN, para malinis ang login pattern at protektado ang account." },
  "why.r3.title": { en: "Strict Offline Mode", zh: "严格离线模式", es: "Modo offline estricto", pt: "Modo offline rigoroso", ru: "Строгий офлайн-режим", fil: "Strict na Offline Mode" },
  "why.r3.desc": { en: "Boosters play in offline / invisible mode, so your activity stays hidden from friends, clubs, and recent teammates.", zh: "代练以离线/隐身模式游戏，让您的活动对好友、战队和近期队友保持隐藏。", es: "Los boosters juegan en modo offline/invisible, para que tu actividad quede oculta de amigos, clubes y compañeros recientes.", pt: "Os boosters jogam em modo offline/invisível, mantendo sua atividade oculta de amigos, clubes e colegas recentes.", ru: "Бустеры играют в офлайн/невидимом режиме, скрывая вашу активность от друзей, клубов и недавних тиммейтов.", fil: "Naglalaro ang boosters sa offline/invisible mode, kaya nakatago ang aktibidad mo sa mga kaibigan, club, at kakalaro." },
  "why.r4.title": { en: "Fast Delivery", zh: "快速交付", es: "Entrega rápida", pt: "Entrega rápida", ru: "Быстрое выполнение", fil: "Mabilis na Delivery" },
  "why.r4.desc": { en: "Most orders start within hours. Need it faster? Priority delivery moves you to the front of the queue.", zh: "大多数订单在数小时内开始。需要更快？优先交付让您排到队列前列。", es: "La mayoría de los pedidos empiezan en horas. ¿Lo quieres antes? La entrega prioritaria te pone al frente de la cola.", pt: "A maioria dos pedidos começa em horas. Precisa mais rápido? A entrega prioritária te coloca à frente da fila.", ru: "Большинство заказов стартует в течение часов. Нужно быстрее? Приоритетная доставка двигает вас в начало очереди.", fil: "Karamihan ng order, nagsisimula sa loob ng ilang oras. Gusto mas mabilis? Inuuna ka ng Priority delivery." },
  "why.r5.title": { en: "Secure & Encrypted", zh: "安全且加密", es: "Seguro y cifrado", pt: "Seguro e criptografado", ru: "Безопасно и зашифровано", fil: "Secure at Naka-encrypt" },
  "why.r5.desc": { en: "Credentials are encrypted at rest and access is audit-logged. Or pick Duo Queue and never share your account at all.", zh: "凭证静态加密，所有访问均有审计记录。或选择双排，完全无需分享账号。", es: "Las credenciales se cifran en reposo y todo acceso queda registrado. O elige Dúo y nunca compartas tu cuenta.", pt: "As credenciais são criptografadas e todo acesso é registrado. Ou escolha Dupla e nunca compartilhe sua conta.", ru: "Учётные данные шифруются, доступ логируется. Или выберите Дуо и вообще не делитесь аккаунтом.", fil: "Naka-encrypt ang credentials at naka-audit-log ang access. O piliin ang Duo Queue at huwag nang i-share ang account." },
  "why.r6.title": { en: "Customer Support", zh: "客户支持", es: "Atención al cliente", pt: "Suporte ao cliente", ru: "Поддержка клиентов", fil: "Customer Support" },
  "why.r6.desc": { en: "Real humans, around the clock. Chat directly with your booster and reach support any time during your order.", zh: "全天候真人服务。直接与您的代练沟通，订单期间随时联系支持。", es: "Personas reales, las 24 horas. Chatea con tu booster y contacta a soporte en cualquier momento.", pt: "Pessoas reais, 24 horas. Converse com seu booster e fale com o suporte a qualquer momento.", ru: "Живые люди круглосуточно. Общайтесь с бустером и обращайтесь в поддержку в любое время.", fil: "Tunay na tao, 24 oras. Makipag-chat sa booster mo at kontakin ang support anumang oras." },

  // ── Guarantees ──────────────────────────────────────────────
  "g.g1.title": { en: "Money-Back Guarantee", zh: "退款保证", es: "Garantía de devolución", pt: "Garantia de reembolso", ru: "Гарантия возврата", fil: "Money-Back Guarantee" },
  "g.g1.desc": { en: "If we can't deliver what was promised, you're protected. Verified concerns are eligible for a full refund.", zh: "如果我们无法兑现承诺，您将受到保护。经核实的问题可获全额退款。", es: "Si no podemos cumplir lo prometido, estás protegido. Los reclamos verificados pueden recibir reembolso completo.", pt: "Se não entregarmos o prometido, você está protegido. Reclamações verificadas têm direito a reembolso total.", ru: "Если мы не выполним обещанное, вы защищены. Подтверждённые претензии — полный возврат.", fil: "Kung hindi namin maibigay ang ipinangako, protektado ka. Ang verified na reklamo ay may full refund." },
  "g.g2.title": { en: "Verified Players Only", zh: "仅限认证玩家", es: "Solo jugadores verificados", pt: "Apenas jogadores verificados", ru: "Только проверенные игроки", fil: "Verified Players Lang" },
  "g.g2.desc": { en: "Every booster is a vetted Immortal with a proven record. No bots, no scripts — real high-MMR gameplay.", zh: "每位代练都是经过审核、战绩可查的万古玩家。无机器人、无脚本——真实的高分对局。", es: "Cada booster es un Inmortal verificado con historial. Sin bots ni scripts — juego real de alto MMR.", pt: "Cada booster é um Immortal verificado com histórico. Sem bots, sem scripts — jogo real de alto MMR.", ru: "Каждый бустер — проверенный Immortal с историей. Без ботов и скриптов — реальная игра на высоком MMR.", fil: "Bawat booster ay vetted Immortal na may record. Walang bot, walang script — totoong high-MMR gameplay." },
  "g.g3.title": { en: "Secure Payments", zh: "安全支付", es: "Pagos seguros", pt: "Pagamentos seguros", ru: "Безопасные платежи", fil: "Secure na Bayad" },
  "g.g3.desc": { en: "Pay safely with Stripe or GCash. Encrypted checkout, and your order is confirmed only after payment clears.", zh: "通过 Stripe 或 GCash 安全付款。加密结账，付款到账后才确认订单。", es: "Paga seguro con Stripe o GCash. Pago cifrado, y tu pedido se confirma solo tras recibir el pago.", pt: "Pague com segurança via Stripe ou GCash. Checkout criptografado, e o pedido só é confirmado após o pagamento.", ru: "Платите безопасно через Stripe или GCash. Зашифрованная оплата, заказ подтверждается только после платежа.", fil: "Magbayad nang ligtas via Stripe o GCash. Naka-encrypt na checkout, at kumpirmado lang ang order pagkatapos ng bayad." },
  "g.g4.title": { en: "Account Safety First", zh: "账号安全优先", es: "Seguridad de cuenta primero", pt: "Segurança da conta primeiro", ru: "Безопасность аккаунта прежде всего", fil: "Account Safety Muna" },
  "g.g4.desc": { en: "VPN matching, offline mode, and strict privacy. Or go Duo and never share your account at all.", zh: "VPN 匹配、离线模式和严格隐私保护。或选择双排，完全无需分享账号。", es: "VPN de tu región, modo offline y privacidad estricta. O ve en Dúo y nunca compartas tu cuenta.", pt: "VPN da sua região, modo offline e privacidade rigorosa. Ou vá de Dupla e nunca compartilhe sua conta.", ru: "VPN вашего региона, офлайн-режим и строгая приватность. Или играйте в Дуо и не делитесь аккаунтом.", fil: "VPN matching, offline mode, at strict na privacy. O mag-Duo at huwag nang i-share ang account." },

  // ── FAQ ─────────────────────────────────────────────────────
  "faq.q1": { en: "Is boosting safe for my account?", zh: "代练对我的账号安全吗？", es: "¿Es seguro el boosting para mi cuenta?", pt: "O boosting é seguro para minha conta?", ru: "Безопасен ли буст для моего аккаунта?", fil: "Ligtas ba ang boosting para sa account ko?" },
  "faq.a1": { en: "Yes. Our boosters use VPN matching your region and play in offline/invisible mode. We never use scripts or cheats — only genuine high-MMR gameplay. For maximum safety, choose Duo Queue and keep your account in your own hands the entire time.", zh: "是的。我们的代练使用与您地区匹配的 VPN，并以离线/隐身模式游戏。我们绝不使用脚本或作弊——只有真实的高分对局。为了最大程度的安全，请选择双排，全程将账号掌握在自己手中。", es: "Sí. Nuestros boosters usan una VPN de tu región y juegan en modo offline/invisible. Nunca usamos scripts ni trampas — solo juego real de alto MMR. Para máxima seguridad, elige Dúo y mantén tu cuenta en tus manos todo el tiempo.", pt: "Sim. Nossos boosters usam VPN da sua região e jogam em modo offline/invisível. Nunca usamos scripts ou cheats — apenas jogo real de alto MMR. Para máxima segurança, escolha Dupla e mantenha sua conta com você o tempo todo.", ru: "Да. Наши бустеры используют VPN вашего региона и играют в офлайн/невидимом режиме. Мы не используем скрипты или читы — только настоящая игра на высоком MMR. Для максимальной безопасности выберите Дуо и держите аккаунт в своих руках.", fil: "Oo. Gumagamit ang boosters namin ng VPN na tugma sa rehiyon mo at naglalaro sa offline/invisible mode. Hindi kami gumagamit ng script o cheat — totoong high-MMR gameplay lang. Para sa pinakaligtas, piliin ang Duo Queue at hawak mo ang account buong oras." },
  "faq.q2": { en: "How long does a boost take?", zh: "代练需要多长时间？", es: "¿Cuánto tarda un boost?", pt: "Quanto tempo leva um boost?", ru: "Сколько занимает буст?", fil: "Gaano katagal ang boost?" },
  "faq.a2": { en: "Most ranks are completed in 1–3 days each, depending on the MMR range and your account's behavior score. You'll see live progress in your dashboard, and you can enable Priority delivery to move faster.", zh: "大多数段位每段需要 1–3 天完成，具体取决于 MMR 范围和您账号的行为分。您可以在控制台查看实时进度，也可以开启优先交付以加快速度。", es: "La mayoría de los rangos se completan en 1–3 días cada uno, según el rango de MMR y la puntuación de comportamiento. Verás el progreso en vivo en tu panel y puedes activar la entrega prioritaria para ir más rápido.", pt: "A maioria dos ranks leva de 1 a 3 dias cada, dependendo da faixa de MMR e do behavior score da conta. Você vê o progresso ao vivo no painel e pode ativar a entrega prioritária para ir mais rápido.", ru: "Большинство рангов проходится за 1–3 дня каждый, в зависимости от диапазона MMR и behavior score аккаунта. Прогресс виден в кабинете, можно включить приоритетную доставку.", fil: "Karamihan ng rank, natatapos sa 1–3 araw bawat isa, depende sa MMR range at behavior score ng account. Makikita ang live progress sa dashboard, at puwedeng i-enable ang Priority delivery para mas mabilis." },
  "faq.q3": { en: "How do payments work?", zh: "付款是如何运作的？", es: "¿Cómo funcionan los pagos?", pt: "Como funcionam os pagamentos?", ru: "Как работают платежи?", fil: "Paano gumagana ang bayad?" },
  "faq.a3": { en: "We accept secure card payments via Stripe and local GCash transfers. Your order is only confirmed once payment is verified — for GCash, an admin reviews your reference and screenshot, then marks the order paid automatically.", zh: "我们接受通过 Stripe 的安全卡支付和本地 GCash 转账。订单仅在付款验证后才会确认——对于 GCash，管理员会审核您的参考号和截图，然后自动标记订单为已付款。", es: "Aceptamos pagos seguros con tarjeta vía Stripe y transferencias locales por GCash. Tu pedido se confirma solo tras verificar el pago — para GCash, un administrador revisa tu referencia y captura, y luego marca el pedido como pagado.", pt: "Aceitamos pagamentos seguros com cartão via Stripe e transferências locais via GCash. Seu pedido só é confirmado após a verificação — no GCash, um admin revisa sua referência e captura e marca o pedido como pago.", ru: "Мы принимаем безопасные платежи картой через Stripe и местные переводы GCash. Заказ подтверждается только после проверки оплаты — для GCash администратор проверяет ссылку и скриншот, затем отмечает заказ оплаченным.", fil: "Tumatanggap kami ng secure card payment via Stripe at local na GCash transfer. Kumpirmado lang ang order kapag na-verify ang bayad — sa GCash, ire-review ng admin ang reference at screenshot mo, tapos awtomatikong mamarkahan na bayad." },
  "faq.q4": { en: "Can I keep playing on my account?", zh: "我可以继续在我的账号上游戏吗？", es: "¿Puedo seguir jugando en mi cuenta?", pt: "Posso continuar jogando na minha conta?", ru: "Могу ли я продолжать играть на аккаунте?", fil: "Puwede pa ba akong maglaro sa account ko?" },
  "faq.a4": { en: "With MMR Boosting we ask that you don't play ranked while a booster is active, to avoid MMR conflicts. With Duo Queue, you play every game yourself alongside your booster — so you're always in control.", zh: "使用 MMR 代练时，我们请您在代练进行期间不要打天梯，以避免 MMR 冲突。使用双排时，您将与代练一起亲自参与每一局——始终掌控全局。", es: "Con el boost de MMR te pedimos que no juegues clasificatorias mientras un booster está activo, para evitar conflictos de MMR. Con Dúo, juegas cada partida tú mismo junto a tu booster — siempre tienes el control.", pt: "No boost de MMR pedimos que você não jogue ranqueada enquanto um booster está ativo, para evitar conflitos de MMR. Na Dupla, você joga cada partida junto ao seu booster — sempre no controle.", ru: "При бусте MMR мы просим не играть ранкед, пока бустер активен, чтобы избежать конфликтов MMR. В Дуо вы играете каждую игру сами вместе с бустером — всегда под контролем.", fil: "Sa MMR Boosting, hinihiling naming huwag maglaro ng ranked habang aktibo ang booster, para iwas MMR conflict. Sa Duo Queue, ikaw mismo ang naglalaro ng bawat game kasama ang booster — palaging ikaw ang may kontrol." },
  "faq.q5": { en: "What if I'm not satisfied?", zh: "如果我不满意怎么办？", es: "¿Y si no estoy satisfecho?", pt: "E se eu não ficar satisfeito?", ru: "Что если я не доволен?", fil: "Paano kung hindi ako satisfied?" },
  "faq.a5": { en: "You confirm the order only when your target rank is reached. Our support team is available 24/7 to resolve any issue, and verified concerns are eligible for our satisfaction guarantee.", zh: "只有在达到目标段位后您才确认订单。我们的支持团队全天候为您解决任何问题，经核实的问题符合我们的满意保证。", es: "Confirmas el pedido solo cuando se alcanza tu rango objetivo. Nuestro soporte está disponible 24/7 para resolver cualquier problema, y los reclamos verificados entran en nuestra garantía de satisfacción.", pt: "Você confirma o pedido apenas quando o rank-alvo é atingido. Nosso suporte está disponível 24/7 para resolver qualquer problema, e reclamações verificadas entram na nossa garantia de satisfação.", ru: "Вы подтверждаете заказ только при достижении целевого ранга. Поддержка работает 24/7, а подтверждённые претензии попадают под гарантию удовлетворённости.", fil: "Kino-confirm mo lang ang order kapag naabot na ang target rank. Available 24/7 ang support namin para sa anumang isyu, at ang verified na reklamo ay saklaw ng aming satisfaction guarantee." },
  "faq.q6": { en: "Do you offer coaching instead of boosting?", zh: "你们提供教学而不是代练吗？", es: "¿Ofrecen coaching en vez de boosting?", pt: "Vocês oferecem coaching em vez de boosting?", ru: "Предлагаете ли вы коучинг вместо буста?", fil: "May coaching ba kayo imbes na boosting?" },
  "faq.a6": { en: "Absolutely. Our 1-on-1 coaching pairs you with an Immortal coach for replay analysis, drafting, and mechanics. It's the best way to climb permanently with skills that stay yours.", zh: "当然。我们的一对一教学将为您配备一名万古教练，进行录像分析、阵容选择和操作指导。这是凭借真正属于自己的技术永久上分的最佳方式。", es: "Por supuesto. Nuestro coaching 1-a-1 te empareja con un entrenador Inmortal para análisis de repeticiones, draft y mecánicas. Es la mejor forma de subir de forma permanente con habilidades que son tuyas.", pt: "Com certeza. Nosso coaching individual te conecta a um treinador Immortal para análise de replays, draft e mecânica. É a melhor forma de subir de vez com habilidades que ficam com você.", ru: "Конечно. Наш индивидуальный коучинг — это тренер уровня Immortal: разбор реплеев, драфт и механика. Лучший способ подниматься навсегда с навыками, которые остаются вашими.", fil: "Oo naman. Ang 1-on-1 coaching namin ay may Immortal coach para sa replay analysis, drafting, at mechanics. Ito ang pinakamahusay na paraan para umakyat nang permanente gamit ang skill na sa iyo." },

  // ── Final CTA ───────────────────────────────────────────────
  "final.badge": { en: "Risk-free · Satisfaction guaranteed", zh: "零风险 · 满意保证", es: "Sin riesgo · Satisfacción garantizada", pt: "Sem risco · Satisfação garantida", ru: "Без риска · Гарантия удовлетворённости", fil: "Walang risk · Satisfaction guaranteed" },
  "final.lead": { en: "Your next rank is", zh: "你的下一个段位", es: "Tu próximo rango está", pt: "Seu próximo rank está", ru: "Ваш следующий ранг", fil: "Ang susunod mong rank ay" },
  "final.accent": { en: "closer than you think.", zh: "比你想的更近。", es: "más cerca de lo que crees.", pt: "mais perto do que você pensa.", ru: "ближе, чем вы думаете.", fil: "mas malapit kaysa akala mo." },
  "final.desc": { en: "Join competitive players worldwide who climbed with RankUpPH. Premium Dota 2 services across all major regions — get an instant quote and start today.", zh: "加入全球与 RankUpPH 一起上分的竞技玩家。覆盖所有主要服务器的高端 Dota 2 服务——立即获取报价，今天就开始。", es: "Únete a jugadores competitivos de todo el mundo que subieron con RankUpPH. Servicios premium de Dota 2 en todas las grandes regiones — obtén un precio al instante y empieza hoy.", pt: "Junte-se a jogadores competitivos do mundo todo que subiram com a RankUpPH. Serviços premium de Dota 2 em todas as grandes regiões — receba um orçamento instantâneo e comece hoje.", ru: "Присоединяйтесь к игрокам со всего мира, поднявшимся с RankUpPH. Премиум-услуги Dota 2 во всех основных регионах — получите мгновенный расчёт и начните сегодня.", fil: "Sumali sa mga competitive player sa buong mundo na umakyat kasama ang RankUpPH. Premium na Dota 2 services sa lahat ng pangunahing rehiyon — kumuha ng instant quote at magsimula ngayon." },
  "final.note": { en: "Competitive Pricing. Global Coverage. · Secure Payments via Stripe and GCash.", zh: "价格实惠，全球覆盖。 · 通过 Stripe 和 GCash 安全支付。", es: "Precios competitivos. Cobertura global. · Pagos seguros con Stripe y GCash.", pt: "Preços competitivos. Cobertura global. · Pagamentos seguros via Stripe e GCash.", ru: "Конкурентные цены. Глобальное покрытие. · Безопасные платежи через Stripe и GCash.", fil: "Competitive na presyo. Global na saklaw. · Secure na bayad via Stripe at GCash." },
  "final.cta": { en: "Get Your Instant Quote", zh: "立即获取报价", es: "Obtén tu precio al instante", pt: "Receba seu orçamento instantâneo", ru: "Получить мгновенный расчёт", fil: "Kunin ang Instant Quote" },
  "final.browse": { en: "Browse Services", zh: "浏览服务", es: "Ver servicios", pt: "Ver serviços", ru: "Смотреть услуги", fil: "Tingnan ang Serbisyo" },

  // ── Footer ──────────────────────────────────────────────────
  "footer.disclaimer": { en: "Not affiliated with or endorsed by Valve Corporation. Dota 2 is a trademark of Valve.", zh: "与 Valve Corporation 无关，也未获其认可。Dota 2 是 Valve 的商标。", es: "No afiliado ni respaldado por Valve Corporation. Dota 2 es una marca de Valve.", pt: "Não afiliado nem endossado pela Valve Corporation. Dota 2 é marca registrada da Valve.", ru: "Не аффилировано с Valve Corporation и не одобрено ею. Dota 2 — товарный знак Valve.", fil: "Hindi kaugnay o endorsed ng Valve Corporation. Ang Dota 2 ay trademark ng Valve." },
  "footer.col.services": { en: "Services", zh: "服务", es: "Servicios", pt: "Serviços", ru: "Услуги", fil: "Mga Serbisyo" },
  "footer.col.company": { en: "Company", zh: "公司", es: "Empresa", pt: "Empresa", ru: "Компания", fil: "Kompanya" },
  "footer.col.account": { en: "Account", zh: "账户", es: "Cuenta", pt: "Conta", ru: "Аккаунт", fil: "Account" },
  "footer.link.mmr": { en: "MMR Boosting", zh: "MMR 代练", es: "Boost de MMR", pt: "Boost de MMR", ru: "Буст MMR", fil: "MMR Boosting" },
  "footer.link.duo": { en: "Duo Queue", zh: "双人排位", es: "Dúo Queue", pt: "Dupla (Duo)", ru: "Дуо-очередь", fil: "Duo Queue" },
  "footer.link.coaching": { en: "Coaching", zh: "教学", es: "Coaching", pt: "Coaching", ru: "Коучинг", fil: "Coaching" },
  "footer.link.calc": { en: "Pricing Calculator", zh: "价格计算器", es: "Calculadora de precios", pt: "Calculadora de preços", ru: "Калькулятор цен", fil: "Pricing Calculator" },
  "footer.link.why": { en: "Why RankUpPH", zh: "为何选择 RankUpPH", es: "Por qué RankUpPH", pt: "Por que a RankUpPH", ru: "Почему RankUpPH", fil: "Bakit RankUpPH" },
  "footer.link.reviews": { en: "Reviews", zh: "用户评价", es: "Reseñas", pt: "Avaliações", ru: "Отзывы", fil: "Mga Review" },
  "footer.link.faq": { en: "FAQ", zh: "常见问题", es: "Preguntas frecuentes", pt: "Perguntas frequentes", ru: "Частые вопросы", fil: "FAQ" },
  "footer.link.becomeBooster": { en: "Become a Booster", zh: "成为代练", es: "Conviértete en booster", pt: "Seja um booster", ru: "Стать бустером", fil: "Maging Booster" },
  "footer.link.createAccount": { en: "Create account", zh: "创建账户", es: "Crear cuenta", pt: "Criar conta", ru: "Создать аккаунт", fil: "Gumawa ng account" },
  "footer.copyright": { en: "All rights reserved.", zh: "版权所有。", es: "Todos los derechos reservados.", pt: "Todos os direitos reservados.", ru: "Все права защищены.", fil: "Lahat ng karapatan ay nakalaan." },
  "footer.serving": { en: "Serving Dota 2 players worldwide · Secure payments via Stripe & GCash", zh: "服务全球 Dota 2 玩家 · 通过 Stripe 和 GCash 安全支付", es: "Al servicio de jugadores de Dota 2 en todo el mundo · Pagos seguros con Stripe y GCash", pt: "Atendendo jogadores de Dota 2 no mundo todo · Pagamentos seguros via Stripe e GCash", ru: "Для игроков Dota 2 по всему миру · Безопасные платежи через Stripe и GCash", fil: "Para sa mga Dota 2 player sa buong mundo · Secure na bayad via Stripe at GCash" },

  // ── Referral teaser ─────────────────────────────────────────
  "referral.comingSoon": { en: "Coming soon", zh: "即将推出", es: "Próximamente", pt: "Em breve", ru: "Скоро", fil: "Malapit na" },
  "referral.lead": { en: "Invite a friend,", zh: "邀请好友，", es: "Invita a un amigo,", pt: "Convide um amigo,", ru: "Пригласи друга —", fil: "Mag-imbita ng kaibigan," },
  "referral.accent": { en: "both get rewarded.", zh: "双方都有奖励。", es: "ambos ganan.", pt: "ambos são recompensados.", ru: "награда для обоих.", fil: "parehong may reward." },
  "referral.desc1": { en: "You and your friend each receive", zh: "您和您的好友将各自获得", es: "Tú y tu amigo reciben cada uno", pt: "Você e seu amigo recebem cada um", ru: "Вы и ваш друг получаете по", fil: "Ikaw at kaibigan mo ay tatanggap ng" },
  "referral.desc2": { en: "credit after their first completed order. Real rewards for real recommendations — no spam, no catch.", zh: "代金券（在好友首单完成后）。真实的推荐，真实的奖励——无垃圾信息，无套路。", es: "de crédito tras su primer pedido completado. Recompensas reales por recomendaciones reales — sin spam, sin trampas.", pt: "de crédito após o primeiro pedido concluído dele. Recompensas reais por indicações reais — sem spam, sem pegadinha.", ru: "кредита после первого выполненного заказа друга. Реальные награды за реальные рекомендации — без спама и подвоха.", fil: "credit pagkatapos ng unang completed order niya. Tunay na reward para sa tunay na rekomendasyon — walang spam, walang catch." },
  "referral.cardNote": { en: "Referral rewards are launching soon. Place an order today to be ready.", zh: "推荐奖励即将上线。今天就下单，做好准备。", es: "Las recompensas por referidos llegan pronto. Haz un pedido hoy para estar listo.", pt: "As recompensas por indicação chegam em breve. Faça um pedido hoje para estar pronto.", ru: "Реферальные награды скоро запустятся. Сделайте заказ сегодня, чтобы быть готовым.", fil: "Malapit nang ilunsad ang referral rewards. Mag-order ngayon para handa ka na." },

  // ── Order summary (calculator) ──────────────────────────────
  "os.title": { en: "Order Summary", zh: "订单摘要", es: "Resumen del pedido", pt: "Resumo do pedido", ru: "Сводка заказа", fil: "Buod ng Order" },
  "os.current": { en: "Current", zh: "当前", es: "Actual", pt: "Atual", ru: "Текущий", fil: "Kasalukuyan" },
  "os.target": { en: "Target", zh: "目标", es: "Objetivo", pt: "Alvo", ru: "Цель", fil: "Target" },
  "os.mmrDiff": { en: "MMR difference", zh: "MMR 差值", es: "Diferencia de MMR", pt: "Diferença de MMR", ru: "Разница MMR", fil: "Pagkakaiba ng MMR" },
  "os.estDelivery": { en: "Estimated delivery", zh: "预计交付", es: "Entrega estimada", pt: "Entrega estimada", ru: "Ожидаемое выполнение", fil: "Tantyang Delivery" },
  "os.total": { en: "Total", zh: "总计", es: "Total", pt: "Total", ru: "Итого", fil: "Kabuuan" },
  "os.finalAtCheckout": { en: "Final price confirmed at checkout", zh: "最终价格在结账时确认", es: "Precio final confirmado en el pago", pt: "Preço final confirmado no checkout", ru: "Итоговая цена подтверждается при оплате", fil: "Kumpirmado ang final na presyo sa checkout" },
  "os.firstDiscount": { en: "First-order discount", zh: "首单折扣", es: "Descuento de primer pedido", pt: "Desconto do primeiro pedido", ru: "Скидка на первый заказ", fil: "Diskwento sa Unang Order" },
  "os.youSavePre": { en: "🎉 You save", zh: "🎉 您节省了", es: "🎉 Ahorras", pt: "🎉 Você economiza", ru: "🎉 Вы экономите", fil: "🎉 Nakatipid ka ng" },
  "os.youSaveSuf": { en: "on your first order", zh: "（首单）", es: "en tu primer pedido", pt: "no seu primeiro pedido", ru: "на первом заказе", fil: "sa unang order mo" },
  "os.continue": { en: "Continue to Checkout", zh: "前往结账", es: "Continuar al pago", pt: "Ir para o pagamento", ru: "Перейти к оплате", fil: "Magpatuloy sa Checkout" },
  "os.trust.secure": { en: "Secure Checkout", zh: "安全结账", es: "Pago seguro", pt: "Checkout seguro", ru: "Безопасная оплата", fil: "Secure na Checkout" },
  "os.trust.verified": { en: "Verified Players", zh: "认证玩家", es: "Jugadores verificados", pt: "Jogadores verificados", ru: "Проверенные игроки", fil: "Verified na Players" },
  "os.trust.fast": { en: "Fast Delivery", zh: "快速交付", es: "Entrega rápida", pt: "Entrega rápida", ru: "Быстрое выполнение", fil: "Mabilis na Delivery" },
  "os.trust.support": { en: "24/7 Support", zh: "全天候支持", es: "Soporte 24/7", pt: "Suporte 24/7", ru: "Поддержка 24/7", fil: "24/7 na Suporta" },

  // ── Boosting mode ───────────────────────────────────────────
  "mode.solo": { en: "Solo Boost", zh: "单人代练", es: "Boost Solo", pt: "Boost Solo", ru: "Соло-буст", fil: "Solo Boost" },
  "mode.soloDesc": { en: "Base price", zh: "基础价格", es: "Precio base", pt: "Preço base", ru: "Базовая цена", fil: "Base na presyo" },
  "mode.duo": { en: "Duo Queue", zh: "双人排位", es: "Dúo Queue", pt: "Dupla (Duo)", ru: "Дуо-очередь", fil: "Duo Queue" },
  "mode.label": { en: "Boosting Mode", zh: "代练模式", es: "Modo de boost", pt: "Modo de boost", ru: "Режим буста", fil: "Boosting Mode" },
  "mode.soloLong": { en: "A pro plays on your account until you hit your goal.", zh: "高手将在您的账号上游戏，直到达成目标。", es: "Un pro juega en tu cuenta hasta alcanzar tu meta.", pt: "Um profissional joga na sua conta até atingir sua meta.", ru: "Профи играет на вашем аккаунте до достижения цели.", fil: "May pro na maglalaro sa account mo hanggang maabot ang goal." },
  "mode.duoLong": { en: "Play alongside your booster — 100% safe, you keep playing.", zh: "与您的代练一起游戏——100% 安全，您始终参与。", es: "Juega junto a tu booster — 100% seguro, tú sigues jugando.", pt: "Jogue ao lado do seu booster — 100% seguro, você continua jogando.", ru: "Играйте вместе с бустером — 100% безопасно, вы продолжаете играть.", fil: "Maglaro kasama ang booster mo — 100% ligtas, ikaw pa rin ang naglalaro." },

  // ── Checkout page ───────────────────────────────────────────
  "co.title": { en: "Checkout", zh: "结账", es: "Pago", pt: "Pagamento", ru: "Оформление", fil: "Checkout" },
  "co.order": { en: "Order", zh: "订单", es: "Pedido", pt: "Pedido", ru: "Заказ", fil: "Order" },
  "co.subtotal": { en: "Subtotal", zh: "小计", es: "Subtotal", pt: "Subtotal", ru: "Подытог", fil: "Subtotal" },
  "co.totalDue": { en: "Total due", zh: "应付总额", es: "Total a pagar", pt: "Total a pagar", ru: "К оплате", fil: "Kabuuang Babayaran" },
  "co.savedPre": { en: "You saved", zh: "您节省了", es: "Ahorraste", pt: "Você economizou", ru: "Вы сэкономили", fil: "Nakatipid ka ng" },
  "co.savedFirst": { en: "on your first order", zh: "（首单）", es: "en tu primer pedido", pt: "no seu primeiro pedido", ru: "на первом заказе", fil: "sa unang order mo" },
  "co.savedWith": { en: "with", zh: "使用", es: "con", pt: "com", ru: "с", fil: "gamit ang" },
  "co.haveVoucher": { en: "Have a voucher code?", zh: "有优惠券代码吗？", es: "¿Tienes un código de descuento?", pt: "Tem um código de voucher?", ru: "Есть промокод?", fil: "May voucher code ka ba?" },
  "co.voucherApplied": { en: "applied", zh: "已应用", es: "aplicado", pt: "aplicado", ru: "применён", fil: "na-apply" },
  "co.remove": { en: "Remove", zh: "移除", es: "Quitar", pt: "Remover", ru: "Убрать", fil: "Alisin" },
  "co.enterCode": { en: "Enter code", zh: "输入代码", es: "Ingresa el código", pt: "Insira o código", ru: "Введите код", fil: "Ilagay ang code" },
  "co.apply": { en: "Apply", zh: "应用", es: "Aplicar", pt: "Aplicar", ru: "Применить", fil: "I-apply" },
  "co.choosePayment": { en: "Choose payment method", zh: "选择支付方式", es: "Elige el método de pago", pt: "Escolha a forma de pagamento", ru: "Выберите способ оплаты", fil: "Pumili ng paraan ng bayad" },
  "co.confirmedOnce": { en: "Your order is confirmed once payment clears.", zh: "付款到账后订单即确认。", es: "Tu pedido se confirma una vez recibido el pago.", pt: "Seu pedido é confirmado assim que o pagamento for compensado.", ru: "Заказ подтверждается после поступления оплаты.", fil: "Kumpirmado ang order mo kapag dumating ang bayad." },
  "co.payByCard": { en: "Pay by card", zh: "刷卡支付", es: "Pagar con tarjeta", pt: "Pagar com cartão", ru: "Оплата картой", fil: "Magbayad gamit ang card" },
  "co.or": { en: "or", zh: "或", es: "o", pt: "ou", ru: "или", fil: "o" },
  "co.payGcash": { en: "Pay with GCash", zh: "使用 GCash 支付", es: "Pagar con GCash", pt: "Pagar com GCash", ru: "Оплата через GCash", fil: "Magbayad gamit ang GCash" },
  "co.encrypted": { en: "Payments are encrypted. We never see your card details.", zh: "支付已加密。我们绝不会看到您的卡片信息。", es: "Los pagos están cifrados. Nunca vemos los datos de tu tarjeta.", pt: "Os pagamentos são criptografados. Nunca vemos os dados do seu cartão.", ru: "Платежи зашифрованы. Мы не видим данные вашей карты.", fil: "Naka-encrypt ang bayad. Hindi namin nakikita ang detalye ng card mo." },
  "co.paymentReceived": { en: "Payment received", zh: "已收到付款", es: "Pago recibido", pt: "Pagamento recebido", ru: "Платёж получен", fil: "Natanggap ang Bayad" },
  "co.alreadyPaid": { en: "This order is already paid and being processed.", zh: "此订单已付款，正在处理中。", es: "Este pedido ya está pagado y en proceso.", pt: "Este pedido já foi pago e está sendo processado.", ru: "Этот заказ уже оплачен и обрабатывается.", fil: "Bayad na ang order na ito at pinoproseso na." },
  "co.trackOrder": { en: "Track your order", zh: "追踪您的订单", es: "Sigue tu pedido", pt: "Rastreie seu pedido", ru: "Отследить заказ", fil: "Subaybayan ang order mo" },

  // ── Trust signals (checkout) ────────────────────────────────
  "trustsig.secure": { en: "Secure encrypted payment", zh: "安全加密支付", es: "Pago cifrado seguro", pt: "Pagamento criptografado seguro", ru: "Безопасный зашифрованный платёж", fil: "Secure na naka-encrypt na bayad" },
  "trustsig.methods": { en: "Stripe & GCash supported", zh: "支持 Stripe 和 GCash", es: "Compatible con Stripe y GCash", pt: "Suporte a Stripe e GCash", ru: "Поддержка Stripe и GCash", fil: "Suportado ang Stripe at GCash" },
  "trustsig.tracking": { en: "Live order tracking", zh: "实时订单追踪", es: "Seguimiento en vivo", pt: "Rastreamento ao vivo", ru: "Отслеживание в реальном времени", fil: "Live na pag-track ng order" },
  "trustsig.boosters": { en: "Verified professional boosters", zh: "认证专业代练", es: "Boosters profesionales verificados", pt: "Boosters profissionais verificados", ru: "Проверенные профи-бустеры", fil: "Verified na propesyonal na booster" },
  "trustsig.support": { en: "24/7 customer support", zh: "全天候客户支持", es: "Soporte al cliente 24/7", pt: "Suporte ao cliente 24/7", ru: "Поддержка клиентов 24/7", fil: "24/7 na customer support" },

  // ── Auth ────────────────────────────────────────────────────
  "auth.login.title": { en: "Welcome back", zh: "欢迎回来", es: "Bienvenido de nuevo", pt: "Bem-vindo de volta", ru: "С возвращением", fil: "Maligayang pagbabalik" },
  "auth.login.subtitle": { en: "Sign in to manage your orders and track progress.", zh: "登录以管理您的订单并追踪进度。", es: "Inicia sesión para gestionar tus pedidos y seguir el progreso.", pt: "Entre para gerenciar seus pedidos e acompanhar o progresso.", ru: "Войдите, чтобы управлять заказами и следить за прогрессом.", fil: "Mag-sign in para i-manage ang order at i-track ang progreso." },
  "auth.google.signin": { en: "Sign in with Google", zh: "使用 Google 登录", es: "Iniciar sesión con Google", pt: "Entrar com o Google", ru: "Войти через Google", fil: "Mag-sign in gamit ang Google" },
  "auth.google.signup": { en: "Sign up with Google", zh: "使用 Google 注册", es: "Registrarse con Google", pt: "Cadastrar com o Google", ru: "Зарегистрироваться через Google", fil: "Mag-sign up gamit ang Google" },
  "auth.email": { en: "Email", zh: "邮箱", es: "Correo", pt: "E-mail", ru: "Эл. почта", fil: "Email" },
  "auth.password": { en: "Password", zh: "密码", es: "Contraseña", pt: "Senha", ru: "Пароль", fil: "Password" },
  "auth.confirm": { en: "Confirm", zh: "确认密码", es: "Confirmar", pt: "Confirmar", ru: "Подтвердите", fil: "Kumpirmahin" },
  "auth.name": { en: "Name", zh: "姓名", es: "Nombre", pt: "Nome", ru: "Имя", fil: "Pangalan" },
  "auth.signin": { en: "Sign in", zh: "登录", es: "Iniciar sesión", pt: "Entrar", ru: "Войти", fil: "Mag-sign in" },
  "auth.noAccount": { en: "Don't have an account?", zh: "还没有账户？", es: "¿No tienes una cuenta?", pt: "Não tem uma conta?", ru: "Нет аккаунта?", fil: "Wala ka pang account?" },
  "auth.createOne": { en: "Create one", zh: "立即创建", es: "Crea una", pt: "Crie uma", ru: "Создать", fil: "Gumawa" },
  "auth.reg.title": { en: "Create your account", zh: "创建您的账户", es: "Crea tu cuenta", pt: "Crie sua conta", ru: "Создайте аккаунт", fil: "Gumawa ng account" },
  "auth.reg.subtitle": { en: "Join thousands of players climbing with RankUpPH.", zh: "加入成千上万与 RankUpPH 一起上分的玩家。", es: "Únete a miles de jugadores que suben con RankUpPH.", pt: "Junte-se a milhares de jogadores que sobem com a RankUpPH.", ru: "Присоединяйтесь к тысячам игроков, поднимающихся с RankUpPH.", fil: "Sumali sa libu-libong manlalaro na umaakyat kasama ang RankUpPH." },
  "auth.createAccount": { en: "Create account", zh: "创建账户", es: "Crear cuenta", pt: "Criar conta", ru: "Создать аккаунт", fil: "Gumawa ng account" },
  "auth.haveAccount": { en: "Already have an account?", zh: "已有账户？", es: "¿Ya tienes una cuenta?", pt: "Já tem uma conta?", ru: "Уже есть аккаунт?", fil: "May account ka na?" },

  // ── Track order ─────────────────────────────────────────────
  "track.eyebrow": { en: "Track Order", zh: "订单追踪", es: "Seguir pedido", pt: "Rastrear pedido", ru: "Отслеживание заказа", fil: "Subaybayan ang Order" },
  "track.titleLead": { en: "Where's my", zh: "我的上分", es: "¿Dónde está mi", pt: "Onde está minha", ru: "Где мой", fil: "Nasaan na ang aking" },
  "track.titleAccent": { en: "climb?", zh: "进度如何？", es: "ascenso?", pt: "subida?", ru: "прогресс?", fil: "pag-akyat?" },
  "track.desc": { en: "Enter your order number to see live status and progress. No sign-in required.", zh: "输入您的订单号即可查看实时状态和进度。无需登录。", es: "Ingresa tu número de pedido para ver el estado y progreso en vivo. Sin necesidad de iniciar sesión.", pt: "Digite o número do pedido para ver status e progresso ao vivo. Sem necessidade de login.", ru: "Введите номер заказа, чтобы увидеть статус и прогресс. Вход не требуется.", fil: "Ilagay ang order number para makita ang live na status at progreso. Hindi kailangan mag-sign in." },

  // ── Calculator configurator ─────────────────────────────────
  "calc.currentMmr": { en: "Current MMR", zh: "当前 MMR", es: "MMR actual", pt: "MMR atual", ru: "Текущий MMR", fil: "Kasalukuyang MMR" },
  "calc.currentMedal": { en: "Current Medal (MMR)", zh: "当前段位（MMR）", es: "Medalla actual (MMR)", pt: "Medalha atual (MMR)", ru: "Текущая медаль (MMR)", fil: "Kasalukuyang Medalya (MMR)" },
  "calc.targetMmr": { en: "Target MMR", zh: "目标 MMR", es: "MMR objetivo", pt: "MMR alvo", ru: "Целевой MMR", fil: "Target na MMR" },
};

export const TRANSLATION_KEYS = Object.keys(T);

/**
 * Translate a key for a locale. Checks UI strings then the catalog map.
 * `fallback` (e.g. the original DB text) is used when no translation exists,
 * so untranslated catalog items render their English source — never a raw key.
 */
export function translate(locale: Locale, key: string, fallback?: string): string {
  return (
    T[key]?.[locale] ??
    CATALOG[key]?.[locale] ??
    T[key]?.en ??
    CATALOG[key]?.en ??
    fallback ??
    key
  );
}
